[package]
name = "freighter"
version = "0.2.0"
edition = "2021"
license = "MIT"
homepage = ""
repository = "https://github.com/open-rust-Initiative/freighter"
documentation = ""
readme = "README.md"
description = """

"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
thiserror = "1.0.36"
clap = "4.0.29"
git2 = "0.16.0"
git2-curl = "0.16"
url = "2.2.2"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
walkdir = "2.3.2"
reqwest = { version = "0.11.13", features = ["blocking"] }
timer = "0.2.0"
chrono = "0.4.22"
rand = "0.8.5"
sha2 = "0.10.5"
threadpool = "1.8.1"
dirs = "4.0.0"
toml = "0.5.8"
log4rs = {version = "1.2.0", features = ["toml_format"] }
log = "0.4.17"
tokio = { version = "1.22.0", features = ["full"] }
warp = { version = "0.3.3", features = ["tls"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
tracing = "0.1"
tracing-subscriber = "0.3"
bytes = "1.1.0"


[dev-dependencies]


[build-dependencies]
