[package]
name = "freighter"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = ""
repository = "https://github.com/open-rust-Initiative/freighter"
documentation = ""
readme = "README.md"
description = """

"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.63"
thiserror = "1.0.36"
clap = "4.0.12"
git2 = "0.15.0"
url = "2.2.2"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
walkdir = "2.3.2"
reqwest = { version = "0.11.11", features = ["blocking"] }
timer = "0.2.0"
chrono = "0.4.22"
rand = "0.8.5"
sha2 = "0.10.5"
sea-orm = { version = "0.9.3", features = [ "sqlx-mysql", "runtime-tokio-rustls", "macros" ] }
threadpool = "1.8.1"
dirs = "4.0.0"


[dev-dependencies]


[build-dependencies]